source ~/.vim/plugins.vim
source ~/.vim/mappings.vim
source ~/.vim/functions.vim

set hidden " Do not unload abandoned buffers
set backspace=indent,eol,start " Allow backspace
set mouse=n " Allow scrolling in normal mode
set autoread " Auto reload if file changes outside of vim
set number " Show line numbers
set relativenumber " Show relative line numbers
set noeb vb t_vb= " Disable beep
set nowrap " Don't wrap lines
set linebreak " Break lines at words when wrap

" Fixes ESC delay
set timeoutlen=1000 
set ttimeoutlen=0 

" Tab
set smarttab
set expandtab
set autoindent
set tabstop=2 shiftwidth=2 softtabstop=2

" Backup handling
set noswapfile
set undodir=~/.vim/undodir
set undofile

" Clipboard
set clipboard=unnamed,unnamedplus

" Show col,row at bottom
set ruler

" Don't polute home directory with viminfo
set viminfo+=n~/.vim/viminfo

" Disables automatic commenting on newline
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

" Syntax Highlighting
" if (has("termguicolors"))
  " set termguicolors
  " set t_8f=[38;2;%lu;%lu;%lum
  " set t_8b=[48;2;%lu;%lu;%lum
" endif

syntax enable
colorscheme nord

" Create Rg command for fzf
command! -bang -nargs=* Rg
  \ call fzf#vim#grep(
  \   'rg --column --line-number --no-heading --color=always --smart-case '.shellescape(<q-args>), 1,
  \   <bang>0 ? fzf#vim#with_preview('up:60%')
  \           : fzf#vim#with_preview('right:50%:hidden', '?'),
  \   <bang>0)

filetype plugin indent on
